#!/bin/bash

#Добавляем репозитории
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt-get update

#Устанавливаем mongodb
sudo apt-get install -y mongodb-org

#Запускаем
sudo systemctl start mongod
sudo systemctl status mongod
sudo systemctl enable mongod
